//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileBuddyUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UITexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UITexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FileBuddyUI.UITexts", typeof(UITexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looks like we were not able to log you in....
        /// </summary>
        internal static string AuthentificationFailed {
            get {
                return ResourceManager.GetString("AuthentificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag file here.
        /// </summary>
        internal static string DragFileHere {
            get {
                return ResourceManager.GetString("DragFileHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ups! Something went wrong!.
        /// </summary>
        internal static string ExceptionThrown {
            get {
                return ResourceManager.GetString("ExceptionThrown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File will already be shared..
        /// </summary>
        internal static string FileIsAlreadyShared {
            get {
                return ResourceManager.GetString("FileIsAlreadyShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File names may not contain blanks!.
        /// </summary>
        internal static string FilenameWithBlanks {
            get {
                return ResourceManager.GetString("FilenameWithBlanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File was saved at {0}..
        /// </summary>
        internal static string FileSavedAt {
            get {
                return ResourceManager.GetString("FileSavedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given mail address is invalid!.
        /// </summary>
        internal static string InvalidMailAddress {
            get {
                return ResourceManager.GetString("InvalidMailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail address and password field is empty!.
        /// </summary>
        internal static string NoDataLoginError {
            get {
                return ResourceManager.GetString("NoDataLoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To successfully register username, mail address and password need to be provided..
        /// </summary>
        internal static string NoDataRegister {
            get {
                return ResourceManager.GetString("NoDataRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No mail address was given!.
        /// </summary>
        internal static string NoMailAddressGiven {
            get {
                return ResourceManager.GetString("NoMailAddressGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files were received..
        /// </summary>
        internal static string NoNewFiles {
            get {
                return ResourceManager.GetString("NoNewFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No password was given!.
        /// </summary>
        internal static string NoPasswordGiven {
            get {
                return ResourceManager.GetString("NoPasswordGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No username was given!.
        /// </summary>
        internal static string NoUsernameGiven {
            get {
                return ResourceManager.GetString("NoUsernameGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files are available for you to download..
        /// </summary>
        internal static string ReceivedFiles {
            get {
                return ResourceManager.GetString("ReceivedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release file.
        /// </summary>
        internal static string ReleaseFile {
            get {
                return ResourceManager.GetString("ReleaseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files were successfully shared!.
        /// </summary>
        internal static string SentFiles {
            get {
                return ResourceManager.GetString("SentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share now!.
        /// </summary>
        internal static string ShareNow {
            get {
                return ResourceManager.GetString("ShareNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file(s) were successfully uploaded!.
        /// </summary>
        internal static string SuccessfullUpload {
            get {
                return ResourceManager.GetString("SuccessfullUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome back {0}!.
        /// </summary>
        internal static string WelcomeBack {
            get {
                return ResourceManager.GetString("WelcomeBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to FileBuddy!.
        /// </summary>
        internal static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
    }
}
